#!/usr/bin/env python3
"""Build docs/results/gallery/ from outputs/ validation artifacts.

Converts generated images to compact WebP previews (git-friendly), links
each to its receipt, and writes an index README. Run after validate.sh.
"""
import hashlib
import json
import os
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow required — run inside the project venv")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = f"{ROOT}/outputs/validation"
GAL = f"{ROOT}/docs/results/gallery"
RECEIPTS = f"{ROOT}/docs/results/validation"
MAX_SIDE = 832
QUALITY = 72


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 22), b""):
            h.update(chunk)
    return h.hexdigest()


def receipt_for(block):
    p = f"{RECEIPTS}/{block}.json"
    return json.load(open(p)) if os.path.isfile(p) else {}


def to_webp(src, dst):
    im = Image.open(src)
    im.thumbnail((MAX_SIDE, MAX_SIDE))
    im.save(dst, "WEBP", quality=QUALITY)
    return im.size


def main():
    os.makedirs(GAL, exist_ok=True)
    entries = []

    def add(title, block, src, note=""):
        if not os.path.isfile(src):
            return
        name = os.path.splitext(os.path.basename(src))[0] + ".webp"
        dst = f"{GAL}/{name}"
        w, h = to_webp(src, dst)
        r = receipt_for(block)
        arts = r.get("artifacts", {}).get(os.path.abspath(src), {})
        entries.append({
            "title": title, "file": name, "src": os.path.relpath(src, ROOT),
            "size": f"{w}×{h}", "block": block,
            "wall_s": r.get("wall_seconds"), "vram_gib": r.get("peak_vram_gib"),
            "sha256_12": arts.get("sha256", "")[:12], "note": note,
        })

    add("T2I — mountain village at sunrise (2048×2048, 50 steps, seed 42)",
        "t2i", f"{OUT}/t2i-2048.png")
    add("T2I + think — peacock display (2048×2048, reasoning mode)",
        "t2i-think", f"{OUT}/t2i-think.png",
        "reasoning text in outputs/validation/t2i-think.think.txt")
    add("Edit — jacket recolored to yellow",
        "edit", f"{OUT}/edit-jacket.png")
    add("Determinism probe A — lantern in snow (20 steps)",
        "determinism", f"{OUT}/determinism-a.png")
    add("Determinism probe B — byte-identical to A",
        "determinism", f"{OUT}/determinism-b.png")
    # interleave outputs
    idir = f"{OUT}/interleave"
    if os.path.isdir(idir):
        for f in sorted(os.listdir(idir)):
            if f.endswith(".png") or f.endswith(".jpg"):
                src = f"{idir}/{f}"
                add(f"Interleave — {f}", "interleave", src)
                # receipts register per-image artifacts when present; fall back to hashing directly
                if not entries[-1]["sha256_12"]:
                    entries[-1]["sha256_12"] = sha256(src)[:12]
        txt = [f for f in sorted(os.listdir(idir)) if f.endswith(".txt")]
        if txt:
            entries.append({"title": f"Interleave text — {txt[0]}",
                            "file": None, "src": f"outputs/validation/interleave/{txt[0]}",
                            "size": "-", "block": "interleave", "wall_s": None,
                            "vram_gib": None, "sha256_12": "", "note": "text part of the interleaved answer"})

    # poster showcase (examples/posters-2026-08.jsonl)
    posters = [
        ("八仙！ — animated fantasy poster (1664×2496, 50 steps)", "baxian"),
        ("THE ODYSSEY — epic mythology poster", "the-odyssey"),
        ("功夫女足 — sports comedy poster (regenerated trademark-clean)", "kungfu-girls"),
        ("欢迎来龙餐馆 — fantasy comedy poster", "dragon-restaurant"),
    ]
    os.makedirs(f"{GAL}/posters", exist_ok=True)
    for title, slug in posters:
        src = f"{ROOT}/outputs/posters/{slug}.png"
        webp = f"{GAL}/posters/{slug}.webp"
        if os.path.isfile(src):
            to_webp(src, webp)
            entries.append({"title": title, "file": f"posters/{slug}.webp",
                            "src": os.path.relpath(src, ROOT), "size": "1664×2496",
                            "block": None, "wall_s": "~300 s",
                            "vram_gib": "22", "sha256_12": sha256(src)[:12],
                            "note": "prompt+seed in examples/posters-2026-08.jsonl; log docs/results/logs/posters.log"})

    stack = receipt_for("t2i").get("rocm_stack")
    stack_note = ("full-stack ROCm 7.14 mode" if stack == "full-stack"
                  else "BLAS-workaround mode")
    lines = [
        "# Validation gallery", "",
        "Generated by `scripts/validate.sh` on the reference host "
        f"(gfx1100, {stack_note}). Full-resolution originals live in "
        "`outputs/validation/` (not committed); each preview links to its "
        "receipt in `docs/results/validation/`.", "",
    ]
    for e in entries:
        if e["file"]:
            meta = f" — wall {e['wall_s']}, peak {e['vram_gib']} GiB" if e["wall_s"] else ""
            receipt = (f"receipt: [{e['block']}.json](../validation/{e['block']}.json), "
                       if e.get("block") else "")
            lines.append(f"### {e['title']}")
            lines.append(f"![{e['title']}]({e['file']})")
            lines.append(f"`{e['src']}`{meta} — {receipt}"
                         f"sha256[:12] `{e['sha256_12']}`{(' — ' + e['note']) if e['note'] else ''}")
            lines.append("")
        else:
            lines.append(f"### {e['title']}")
            lines.append(f"text: `{e['src']}` — receipt: [interleave.json](../validation/interleave.json)")
            lines.append("")
    with open(f"{GAL}/README.md", "w") as fh:
        fh.write("\n".join(lines))
    print(f"gallery: {len(entries)} entries -> {GAL}/README.md")


if __name__ == "__main__":
    main()
